[package]
name = "gd3_meshopt"
version = "0.1.0"
authors = ["Tim Kluge <timklge@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gdnative = "0.11.0"
meshopt = "0.1.9"
# gdnative = { path = "../../godot-rust/gdnative" }